apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskml
spec:
  selector:
    matchLabels:
      app: flaskml
  template:
    metadata:
      labels:
        app: flaskml
    spec:
      containers:
      - name: flaskml
        image: <your image deployed to dockerhub>
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flaskml-service
spec:
  type: NodePort
  selector:
    app: flaskml
  ports:
  - port: 8000
    targetPort: 5000
    nodePort: 31000